<?php ;
    return array(
        "status_100" => "100",
        "message_100" => "Request has been received",
        "status_200" => "200",
        "message_200" => "Request processed successfully",
        "status_2xx" => "2xx",
        "message_2xx" => "",
        "status_301" => "301",
        "message_301" => "Request should be sent to another address",
        "status_400" => "400",
        "message_400" => "The request is not valid",
        "status_401" => "401",
        "message_401" => "Request not granted",
        "status_403" => "403",
        "message_403" => "Access prohibited request",
        "status_404" => "404",
        "message_404" => "Request did not exist, could not be found",
        "status_405" => "405",
        "message_405" => "The method is not valid",
        "status_406" => "406",
        "message_406" => "Not accepted",
        "status_410" => "410",
        "message_410" => "Request no longer usable",
        "status_429" => "429",
        "message_429" => "Too many requests, restricting receiving requests",
        "status_500" => "500",
        "message_500" => "Internal server error",
        "status_503" => "503",
        "message_503" => "Service not working"
    );
?>